# Generated by Django 6.0.3 on 2026-04-06 10:52

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('author_name', models.CharField(max_length=255, null=True)),
                ('author_name_bn', models.CharField(blank=True, max_length=255, null=True)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('title', models.CharField(max_length=255, null=True)),
                ('title_bn', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle_bn', models.CharField(blank=True, max_length=255, null=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(null=True)),
                ('content_bn', django_ckeditor_5.fields.CKEditor5Field(null=True)),
                ('cover_image', models.ImageField(null=True, upload_to='blog_images/')),
                ('read_time', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('index_number', models.IntegerField(default=0, help_text='Order of the blog post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
